### ISSUE TITLE
Dependency conflict between expo-camera & @tensorflow/tfjs-react-native

### ISSUE THREAD

**Issue by Modmaster2000** [kev0051/DustblockBlues#3]
Dependency conflict between the version of expo-camera & @tensorflow/tfjs-react-native (versions 13.4.4 vs. 7.0.0). Lines related to the @tensorflow/tfjs-react-native module have been commented out. 
![image](https://github.com/kev0051/DustblockBlues/assets/78181793/5a54f124-8178-46dd-b5ed-3a589beeb9cc)

**Comment by ReedNathan001** [comment]
project works on expo47
